name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Pacman
    steps:
      - uses: actions/checkout@v3
      - uses: abhisheknaiidu/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          output: pacman-output/pacman-contribution-graph.svg
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: generate pacman contribution graph"
          branch: main
          file_pattern: pacman-output/
